apiVersion: app/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: expense-tracker-flask
          image: icr.io/expense_tracker_flask/expense_tracker
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  type: nodePort
  selector:
    app: expense-tracker
  ports:
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
